name: iubdc
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pandas
  - numpy
  - scikit-learn
  - py-xgboost-gpu
  - matplotlib
  - seaborn
  - jupyterlab
  - ipykernel
  - shap
